/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WettbewerbeRouteImport } from './routes/wettbewerbe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NachhaltigkeitRouteImport } from './routes/nachhaltigkeit'
import { Route as MitgliedersucheRouteImport } from './routes/mitgliedersuche'
import { Route as MitgliederbereichRouteImport } from './routes/mitgliederbereich'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as InnungenRouteImport } from './routes/innungen'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as ImmateriellesKulturerbeRouteImport } from './routes/immaterielles-kulturerbe'
import { Route as GoldSilberschmiedeRouteImport } from './routes/gold-silberschmiede'
import { Route as FortbildungenRouteImport } from './routes/fortbildungen'
import { Route as DerZvRouteImport } from './routes/der-zv'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as BarrierefreiheitRouteImport } from './routes/barrierefreiheit'
import { Route as AusWeiterbildungRouteImport } from './routes/aus-weiterbildung'
import { Route as AktuellRouteImport } from './routes/aktuell'
import { Route as R125JahreRouteImport } from './routes/125-jahre'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'

const WettbewerbeRoute = WettbewerbeRouteImport.update({
  id: '/wettbewerbe',
  path: '/wettbewerbe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NachhaltigkeitRoute = NachhaltigkeitRouteImport.update({
  id: '/nachhaltigkeit',
  path: '/nachhaltigkeit',
  getParentRoute: () => rootRouteImport,
} as any)
const MitgliedersucheRoute = MitgliedersucheRouteImport.update({
  id: '/mitgliedersuche',
  path: '/mitgliedersuche',
  getParentRoute: () => rootRouteImport,
} as any)
const MitgliederbereichRoute = MitgliederbereichRouteImport.update({
  id: '/mitgliederbereich',
  path: '/mitgliederbereich',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const InnungenRoute = InnungenRouteImport.update({
  id: '/innungen',
  path: '/innungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmateriellesKulturerbeRoute = ImmateriellesKulturerbeRouteImport.update({
  id: '/immaterielles-kulturerbe',
  path: '/immaterielles-kulturerbe',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldSilberschmiedeRoute = GoldSilberschmiedeRouteImport.update({
  id: '/gold-silberschmiede',
  path: '/gold-silberschmiede',
  getParentRoute: () => rootRouteImport,
} as any)
const FortbildungenRoute = FortbildungenRouteImport.update({
  id: '/fortbildungen',
  path: '/fortbildungen',
  getParentRoute: () => rootRouteImport,
} as any)
const DerZvRoute = DerZvRouteImport.update({
  id: '/der-zv',
  path: '/der-zv',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const BarrierefreiheitRoute = BarrierefreiheitRouteImport.update({
  id: '/barrierefreiheit',
  path: '/barrierefreiheit',
  getParentRoute: () => rootRouteImport,
} as any)
const AusWeiterbildungRoute = AusWeiterbildungRouteImport.update({
  id: '/aus-weiterbildung',
  path: '/aus-weiterbildung',
  getParentRoute: () => rootRouteImport,
} as any)
const AktuellRoute = AktuellRouteImport.update({
  id: '/aktuell',
  path: '/aktuell',
  getParentRoute: () => rootRouteImport,
} as any)
const R125JahreRoute = R125JahreRouteImport.update({
  id: '/125-jahre',
  path: '/125-jahre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/125-jahre': typeof R125JahreRoute
  '/aktuell': typeof AktuellRoute
  '/aus-weiterbildung': typeof AusWeiterbildungRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/datenschutz': typeof DatenschutzRoute
  '/der-zv': typeof DerZvRoute
  '/fortbildungen': typeof FortbildungenRoute
  '/gold-silberschmiede': typeof GoldSilberschmiedeRoute
  '/immaterielles-kulturerbe': typeof ImmateriellesKulturerbeRoute
  '/impressum': typeof ImpressumRoute
  '/innungen': typeof InnungenRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/mitgliederbereich': typeof MitgliederbereichRoute
  '/mitgliedersuche': typeof MitgliedersucheRoute
  '/nachhaltigkeit': typeof NachhaltigkeitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wettbewerbe': typeof WettbewerbeRoute
  '/api/ai-chat': typeof ApiAiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/125-jahre': typeof R125JahreRoute
  '/aktuell': typeof AktuellRoute
  '/aus-weiterbildung': typeof AusWeiterbildungRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/datenschutz': typeof DatenschutzRoute
  '/der-zv': typeof DerZvRoute
  '/fortbildungen': typeof FortbildungenRoute
  '/gold-silberschmiede': typeof GoldSilberschmiedeRoute
  '/immaterielles-kulturerbe': typeof ImmateriellesKulturerbeRoute
  '/impressum': typeof ImpressumRoute
  '/innungen': typeof InnungenRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/mitgliederbereich': typeof MitgliederbereichRoute
  '/mitgliedersuche': typeof MitgliedersucheRoute
  '/nachhaltigkeit': typeof NachhaltigkeitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wettbewerbe': typeof WettbewerbeRoute
  '/api/ai-chat': typeof ApiAiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/125-jahre': typeof R125JahreRoute
  '/aktuell': typeof AktuellRoute
  '/aus-weiterbildung': typeof AusWeiterbildungRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/datenschutz': typeof DatenschutzRoute
  '/der-zv': typeof DerZvRoute
  '/fortbildungen': typeof FortbildungenRoute
  '/gold-silberschmiede': typeof GoldSilberschmiedeRoute
  '/immaterielles-kulturerbe': typeof ImmateriellesKulturerbeRoute
  '/impressum': typeof ImpressumRoute
  '/innungen': typeof InnungenRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/mitgliederbereich': typeof MitgliederbereichRoute
  '/mitgliedersuche': typeof MitgliedersucheRoute
  '/nachhaltigkeit': typeof NachhaltigkeitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wettbewerbe': typeof WettbewerbeRoute
  '/api/ai-chat': typeof ApiAiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/125-jahre'
    | '/aktuell'
    | '/aus-weiterbildung'
    | '/barrierefreiheit'
    | '/datenschutz'
    | '/der-zv'
    | '/fortbildungen'
    | '/gold-silberschmiede'
    | '/immaterielles-kulturerbe'
    | '/impressum'
    | '/innungen'
    | '/kontakt'
    | '/login'
    | '/mitgliederbereich'
    | '/mitgliedersuche'
    | '/nachhaltigkeit'
    | '/sitemap.xml'
    | '/wettbewerbe'
    | '/api/ai-chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/125-jahre'
    | '/aktuell'
    | '/aus-weiterbildung'
    | '/barrierefreiheit'
    | '/datenschutz'
    | '/der-zv'
    | '/fortbildungen'
    | '/gold-silberschmiede'
    | '/immaterielles-kulturerbe'
    | '/impressum'
    | '/innungen'
    | '/kontakt'
    | '/login'
    | '/mitgliederbereich'
    | '/mitgliedersuche'
    | '/nachhaltigkeit'
    | '/sitemap.xml'
    | '/wettbewerbe'
    | '/api/ai-chat'
  id:
    | '__root__'
    | '/'
    | '/125-jahre'
    | '/aktuell'
    | '/aus-weiterbildung'
    | '/barrierefreiheit'
    | '/datenschutz'
    | '/der-zv'
    | '/fortbildungen'
    | '/gold-silberschmiede'
    | '/immaterielles-kulturerbe'
    | '/impressum'
    | '/innungen'
    | '/kontakt'
    | '/login'
    | '/mitgliederbereich'
    | '/mitgliedersuche'
    | '/nachhaltigkeit'
    | '/sitemap.xml'
    | '/wettbewerbe'
    | '/api/ai-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R125JahreRoute: typeof R125JahreRoute
  AktuellRoute: typeof AktuellRoute
  AusWeiterbildungRoute: typeof AusWeiterbildungRoute
  BarrierefreiheitRoute: typeof BarrierefreiheitRoute
  DatenschutzRoute: typeof DatenschutzRoute
  DerZvRoute: typeof DerZvRoute
  FortbildungenRoute: typeof FortbildungenRoute
  GoldSilberschmiedeRoute: typeof GoldSilberschmiedeRoute
  ImmateriellesKulturerbeRoute: typeof ImmateriellesKulturerbeRoute
  ImpressumRoute: typeof ImpressumRoute
  InnungenRoute: typeof InnungenRoute
  KontaktRoute: typeof KontaktRoute
  LoginRoute: typeof LoginRoute
  MitgliederbereichRoute: typeof MitgliederbereichRoute
  MitgliedersucheRoute: typeof MitgliedersucheRoute
  NachhaltigkeitRoute: typeof NachhaltigkeitRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WettbewerbeRoute: typeof WettbewerbeRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wettbewerbe': {
      id: '/wettbewerbe'
      path: '/wettbewerbe'
      fullPath: '/wettbewerbe'
      preLoaderRoute: typeof WettbewerbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nachhaltigkeit': {
      id: '/nachhaltigkeit'
      path: '/nachhaltigkeit'
      fullPath: '/nachhaltigkeit'
      preLoaderRoute: typeof NachhaltigkeitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitgliedersuche': {
      id: '/mitgliedersuche'
      path: '/mitgliedersuche'
      fullPath: '/mitgliedersuche'
      preLoaderRoute: typeof MitgliedersucheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitgliederbereich': {
      id: '/mitgliederbereich'
      path: '/mitgliederbereich'
      fullPath: '/mitgliederbereich'
      preLoaderRoute: typeof MitgliederbereichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innungen': {
      id: '/innungen'
      path: '/innungen'
      fullPath: '/innungen'
      preLoaderRoute: typeof InnungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immaterielles-kulturerbe': {
      id: '/immaterielles-kulturerbe'
      path: '/immaterielles-kulturerbe'
      fullPath: '/immaterielles-kulturerbe'
      preLoaderRoute: typeof ImmateriellesKulturerbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-silberschmiede': {
      id: '/gold-silberschmiede'
      path: '/gold-silberschmiede'
      fullPath: '/gold-silberschmiede'
      preLoaderRoute: typeof GoldSilberschmiedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fortbildungen': {
      id: '/fortbildungen'
      path: '/fortbildungen'
      fullPath: '/fortbildungen'
      preLoaderRoute: typeof FortbildungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/der-zv': {
      id: '/der-zv'
      path: '/der-zv'
      fullPath: '/der-zv'
      preLoaderRoute: typeof DerZvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barrierefreiheit': {
      id: '/barrierefreiheit'
      path: '/barrierefreiheit'
      fullPath: '/barrierefreiheit'
      preLoaderRoute: typeof BarrierefreiheitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aus-weiterbildung': {
      id: '/aus-weiterbildung'
      path: '/aus-weiterbildung'
      fullPath: '/aus-weiterbildung'
      preLoaderRoute: typeof AusWeiterbildungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktuell': {
      id: '/aktuell'
      path: '/aktuell'
      fullPath: '/aktuell'
      preLoaderRoute: typeof AktuellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/125-jahre': {
      id: '/125-jahre'
      path: '/125-jahre'
      fullPath: '/125-jahre'
      preLoaderRoute: typeof R125JahreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R125JahreRoute: R125JahreRoute,
  AktuellRoute: AktuellRoute,
  AusWeiterbildungRoute: AusWeiterbildungRoute,
  BarrierefreiheitRoute: BarrierefreiheitRoute,
  DatenschutzRoute: DatenschutzRoute,
  DerZvRoute: DerZvRoute,
  FortbildungenRoute: FortbildungenRoute,
  GoldSilberschmiedeRoute: GoldSilberschmiedeRoute,
  ImmateriellesKulturerbeRoute: ImmateriellesKulturerbeRoute,
  ImpressumRoute: ImpressumRoute,
  InnungenRoute: InnungenRoute,
  KontaktRoute: KontaktRoute,
  LoginRoute: LoginRoute,
  MitgliederbereichRoute: MitgliederbereichRoute,
  MitgliedersucheRoute: MitgliedersucheRoute,
  NachhaltigkeitRoute: NachhaltigkeitRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WettbewerbeRoute: WettbewerbeRoute,
  ApiAiChatRoute: ApiAiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
